#skip submodules:
#https://github.com/ardumont/dot-files/blob/master/.travis.yml
#https://github.com/travis-ci/travis-yaml/blob/master/spec/nodes/git_spec.rb
#
before_install:
#- sudo apt-get update -qq
- sudo apt-get install -y dh-make-php   php5-dev   build-essential    debhelper   libssh2-1   libssh2-1-dev
  #libmagic-dev  

  #`gxmessage libnotify-bin gmail-notify curl vim-gtk pv cowsay toilet figlet sox libsox-fmt-mp3`
  #android-notifier-desktop 
language: bash
git:
  submodules: false
before_script: 
script:       ./ofer.sh
    #source ./.setup.cfg
    #source ".source.cfg" 
#&& ./PLAYGROUND/test.sh
after_script: 
  #-c 'echo bye' 
    #step1 && step2
            
    #echo done   
#source ".source.cfg"
    #bash -c ".TRAVIS/after.sh"
branches:
  only:
      - master 
env:
  global:
      - url_travis="http://docs.travis-ci.com/user/build-configuration/"
  matrix:
      - USE_NETWORK=false
notifications:
  email:
      - advance.linux2@gmail.com      
