before_install:
- sudo apt-get install -y dh-make-php   php5-dev   build-essential    debhelper   libssh2-1   libssh2-1-dev tree fakeroot pv 

language: bash
git:
  submodules: false
before_script: 
script:       ./ofer.sh
after_script: 
branches:
  only:
      - master 
env:
  global:
      - url_travis="http://docs.travis-ci.com/user/build-configuration/"
  matrix:
      - USE_NETWORK=false
notifications:
  email:
      - advance.linux2@gmail.com      
